# Forked from scratchpad/gemini_runner.py @ 192d8c5460d79ccad8652ab264a64d2680558c38.
# Do NOT edit this file to track scratchpad changes automatically — production and
# research diverge on purpose. Re-sync is a deliberate commit: copy the scratchpad
# file, re-pin the SHA above, re-verify the Phase 1 gate.
from __future__ import annotations

import json
import mimetypes
import subprocess
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Callable


def now_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="milliseconds")


def duration_ms(start_perf: float, end_perf: float | None = None) -> float:
    final = end_perf if end_perf is not None else time.perf_counter()
    return round((final - start_perf) * 1000, 2)


def plain_data(value: Any) -> Any:
    if value is None:
        return None
    if hasattr(value, "model_dump"):
        return plain_data(value.model_dump(exclude_none=True))
    if isinstance(value, (bytes, bytearray, memoryview)):
        return {
            "type": type(value).__name__,
            "length": len(value),
        }
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(key): plain_data(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [plain_data(item) for item in value]
    if isinstance(value, (str, int, float, bool)):
        return value
    for attr in ("x", "y", "width", "height"):
        if hasattr(value, attr):
            break
    else:
        return str(value)

    payload: dict[str, Any] = {}
    for attr in ("x", "y", "width", "height"):
        if hasattr(value, attr):
            payload[attr] = float(getattr(value, attr))
    return payload


def guess_mime_type(path: Path) -> str:
    mime_type, _ = mimetypes.guess_type(path.name)
    if mime_type and mime_type.startswith("image/"):
        return mime_type
    return "image/png"


def prepare_request_image(image_path: Path, settings: dict[str, Any]) -> dict[str, Any]:
    original_bytes = image_path.stat().st_size
    preprocess_enabled = bool(settings.get("preprocess_request_images", True))
    started_perf = time.perf_counter()
    started_at = now_iso()

    if not preprocess_enabled:
        data = image_path.read_bytes()
        finished_at = now_iso()
        return {
            "bytes_data": data,
            "mime_type": guess_mime_type(image_path),
            "original_bytes": original_bytes,
            "request_bytes": len(data),
            "duration_ms": duration_ms(started_perf),
            "log": {
                "status": "original",
                "enabled": False,
                "started_at": started_at,
                "finished_at": finished_at,
                "duration_ms": duration_ms(started_perf),
                "original_path": str(image_path),
                "original_bytes": original_bytes,
                "request_path": str(image_path),
                "request_bytes": len(data),
                "request_mime_type": guess_mime_type(image_path),
            },
        }

    request_format = str(settings.get("request_image_format", "jpeg")).lower()
    max_dimension = int(settings.get("request_image_max_dimension", 1600))
    jpeg_quality = int(settings.get("request_image_jpeg_quality", 80))
    extension = ".jpg" if request_format in {"jpeg", "jpg"} else f".{request_format}"
    request_path = image_path.with_name(f"{image_path.stem}.request{extension}")
    command = ["/usr/bin/sips"]
    if request_format:
        command += ["-s", "format", request_format]
        if request_format in {"jpeg", "jpg"}:
            command += ["-s", "formatOptions", str(jpeg_quality)]
    if max_dimension > 0:
        command += ["-Z", str(max_dimension)]
    command += [str(image_path), "--out", str(request_path)]

    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
    )
    finished_at = now_iso()
    duration = duration_ms(started_perf)

    if result.returncode == 0 and request_path.exists():
        data = request_path.read_bytes()
        return {
            "bytes_data": data,
            "mime_type": guess_mime_type(request_path),
            "original_bytes": original_bytes,
            "request_bytes": len(data),
            "duration_ms": duration,
            "log": {
                "status": "processed",
                "enabled": True,
                "started_at": started_at,
                "finished_at": finished_at,
                "duration_ms": duration,
                "original_path": str(image_path),
                "original_bytes": original_bytes,
                "request_path": str(request_path),
                "request_bytes": len(data),
                "request_mime_type": guess_mime_type(request_path),
                "request_format": request_format,
                "request_image_max_dimension": max_dimension,
                "request_image_jpeg_quality": jpeg_quality
                if request_format in {"jpeg", "jpg"}
                else None,
                "command": command,
                "stdout": (result.stdout or "").strip(),
                "stderr": (result.stderr or "").strip(),
            },
        }

    data = image_path.read_bytes()
    return {
        "bytes_data": data,
        "mime_type": guess_mime_type(image_path),
        "original_bytes": original_bytes,
        "request_bytes": len(data),
        "duration_ms": duration,
        "log": {
            "status": "fallback_original",
            "enabled": True,
            "started_at": started_at,
            "finished_at": finished_at,
            "duration_ms": duration,
            "original_path": str(image_path),
            "original_bytes": original_bytes,
            "request_path": str(image_path),
            "request_bytes": len(data),
            "request_mime_type": guess_mime_type(image_path),
            "request_format": request_format,
            "request_image_max_dimension": max_dimension,
            "request_image_jpeg_quality": jpeg_quality
            if request_format in {"jpeg", "jpg"}
            else None,
            "command": command,
            "stdout": (result.stdout or "").strip(),
            "stderr": (result.stderr or "").strip(),
        },
    }


def normalized_model_name(model: Any) -> str:
    text = str(model or "").strip().lower()
    return text.removeprefix("models/")


def _gemini_thinking_kwargs(model: Any, level: Any) -> dict[str, Any] | None:
    """Map Blink's logical thinking level to Gemini's per-family API shape."""
    if level in {None, "", False}:
        return None
    level_text = str(level).strip()
    if not level_text or level_text.lower() in {"none", "false"}:
        return None

    normalized = normalized_model_name(model)
    upper = level_text.upper()
    if normalized.startswith("gemini-3"):
        return {"include_thoughts": False, "thinking_level": upper}
    if normalized.startswith("gemini-2.5-pro"):
        budget = {
            "MINIMAL": 128,
            "LOW": 256,
            "MEDIUM": 1024,
            "HIGH": 4096,
        }.get(upper, 128)
        return {"include_thoughts": False, "thinking_budget": budget}
    if normalized.startswith("gemini-2.5"):
        budget = {
            "MINIMAL": 0,
            "LOW": 256,
            "MEDIUM": 1024,
            "HIGH": 4096,
        }.get(upper, 0)
        return {"include_thoughts": False, "thinking_budget": budget}
    return None


def thinking_config_kwargs(settings: dict[str, Any]) -> dict[str, Any] | None:
    return _gemini_thinking_kwargs(
        settings.get("model", ""),
        settings.get("thinking_level", "MINIMAL"),
    )


def build_user_parts(
    settings: dict[str, Any],
    source_path: Path,
    target_path: Path,
    target_metadata: dict[str, Any],
) -> tuple[list[Any], dict[str, Any]]:
    from google.genai import types

    prepare_started_perf = time.perf_counter()

    metadata_json = json.dumps(target_metadata, indent=2, ensure_ascii=True)
    instruction_text = (
        "TARGET_METADATA_JSON:\n"
        f"{metadata_json}\n\n"
        "Use the source image as the source context and the target image as the destination context."
    )

    source_request_image = prepare_request_image(source_path, settings)
    target_request_image = prepare_request_image(target_path, settings)

    parts = [
        types.Part.from_text(text=instruction_text),
        types.Part.from_text(text="SOURCE_IMAGE"),
        types.Part.from_bytes(
            data=source_request_image["bytes_data"],
            mime_type=source_request_image["mime_type"],
        ),
        types.Part.from_text(text="TARGET_IMAGE"),
        types.Part.from_bytes(
            data=target_request_image["bytes_data"],
            mime_type=target_request_image["mime_type"],
        ),
    ]

    timings = {
        "request_build_ms": duration_ms(prepare_started_perf),
        "source_image_prepare_ms": source_request_image["duration_ms"],
        "target_image_prepare_ms": target_request_image["duration_ms"],
    }
    inputs = {
        "instruction_chars": len(instruction_text),
        "source_image_bytes": source_request_image["request_bytes"],
        "target_image_bytes": target_request_image["request_bytes"],
        "source_original_image_bytes": source_request_image["original_bytes"],
        "target_original_image_bytes": target_request_image["original_bytes"],
    }
    images = {
        "source": source_request_image["log"],
        "target": target_request_image["log"],
    }
    return parts, {"timings": timings, "inputs": inputs, "images": images}


def build_generation_config(settings: dict[str, Any], prompt_text: str) -> Any:
    from google.genai import types

    config_kwargs: dict[str, Any] = {
        "system_instruction": prompt_text,
        "temperature": settings["temperature"],
        "max_output_tokens": settings["max_output_tokens"],
        "response_mime_type": "text/plain",
        "media_resolution": settings["media_resolution"],
    }

    thinking_kwargs = thinking_config_kwargs(settings)
    if thinking_kwargs is not None:
        config_kwargs["thinking_config"] = types.ThinkingConfig(**thinking_kwargs)

    return types.GenerateContentConfig(**config_kwargs)


def _extract_usage_number(payload: Any, *keys: str) -> Any:
    if not isinstance(payload, dict):
        return None
    for key in keys:
        if key in payload:
            return payload[key]
    return None


def generate_completion(
    client: Any,
    settings: dict[str, Any],
    prompt_text: str,
    source_path: Path,
    target_path: Path,
    target_metadata: dict[str, Any],
    *,
    stream_to_terminal: bool | None = None,
    status_callback: Callable[[str], None] | None = None,
) -> dict[str, Any]:
    from google.genai import types

    output_chunks: list[str] = []
    first_chunk_perf: float | None = None
    final_chunk_perf: float | None = None
    first_chunk_at: str | None = None
    final_chunk_at: str | None = None
    usage_metadata: Any = None
    final_chunk_payload: Any = None

    parts, prep = build_user_parts(settings, source_path, target_path, target_metadata)
    contents = [types.Content(role="user", parts=parts)]
    config = build_generation_config(settings, prompt_text)

    request_send_perf = time.perf_counter()
    request_send_at = now_iso()
    status = "ok"
    error_message = None
    chunk_count = 0
    should_stream = (
        bool(settings.get("stream_to_terminal", True))
        if stream_to_terminal is None
        else bool(stream_to_terminal)
    )

    if status_callback is not None:
        status_callback("gemini streaming...")

    try:
        stream = client.models.generate_content_stream(
            model=settings["model"],
            contents=contents,
            config=config,
        )
        for chunk in stream:
            chunk_count += 1
            chunk_perf = time.perf_counter()
            if first_chunk_perf is None:
                first_chunk_perf = chunk_perf
                first_chunk_at = now_iso()
            final_chunk_perf = chunk_perf
            final_chunk_at = now_iso()
            if getattr(chunk, "text", None):
                text = chunk.text
                output_chunks.append(text)
                if should_stream:
                    print(text, end="", flush=True)
            if getattr(chunk, "usage_metadata", None) is not None:
                usage_metadata = plain_data(chunk.usage_metadata)
            final_chunk_payload = plain_data(chunk)
    except Exception as exc:
        status = "error"
        error_message = str(exc)

    finished_perf = time.perf_counter()
    if final_chunk_perf is None:
        final_chunk_perf = finished_perf

    output_text = "".join(output_chunks).strip()
    candidates_token_count = _extract_usage_number(
        usage_metadata, "candidates_token_count", "candidatesTokenCount"
    )
    stream_duration_ms = None
    output_tps = None
    if first_chunk_perf is not None and final_chunk_perf is not None:
        stream_duration_ms = duration_ms(first_chunk_perf, final_chunk_perf)
        if candidates_token_count and stream_duration_ms and stream_duration_ms > 0:
            output_tps = round(
                float(candidates_token_count) / (stream_duration_ms / 1000.0), 2
            )

    run_log = {
        "status": status,
        "request": {
            "model": settings["model"],
            "request_send_at": request_send_at,
            "prompt_chars": len(prompt_text),
            **prep["inputs"],
            "images": prep["images"],
        },
        "response": {
            "usage_metadata": usage_metadata,
            "chunk_count": chunk_count,
            "response_metadata": final_chunk_payload,
            "output_tps": output_tps,
            "output_text": output_text,
            "output_text_length": len(output_text),
        },
        "timings": {
            **prep["timings"],
            "request_send_at": request_send_at,
            "first_chunk_at": first_chunk_at,
            "final_chunk_at": final_chunk_at,
            "ttft_ms": duration_ms(request_send_perf, first_chunk_perf)
            if first_chunk_perf is not None
            else None,
            "stream_duration_ms": stream_duration_ms,
            "model_latency_ms": duration_ms(request_send_perf, final_chunk_perf),
        },
    }
    if error_message:
        run_log["errors"] = [error_message]
    return {"run_log": run_log, "output_text": output_text}
